tasks:
  capabilities:
    expenses:
      prompt-path: src/main/resources/expenseTrackingPrompt2
      model-name: gemini-3-flash-preview
      real-tool-set: true
  chats:
    - name: "My Group Chat"
      capabilities:
        - expenses

logger:
  output-folder: dev

context:
  storage-path: contexts/
  verbatim-chars: 10000
  summarization-model: gemini-2.0-flash
  summarization-prompt-path: src/main/resources/summarizationPrompt
